ResetZone = ResetZone or {}
ResetZone.ResetCells = {}

-- Load default list if available
require "ResetZoneDefaultList"

-- Helper to get consistent chunk name
function ResetZone.getChunkName(x, y)
    local cellX = math.floor(x / 10)
    local cellY = math.floor(y / 10)
    return string.format("map/%d/%d.bin", cellX, cellY)
end

-- File handling
local filename = "ResetZone_reset_list.txt"

function ResetZone.LoadResetList()
    ResetZone.ResetCells = {}
    local reader = getFileReader(filename, true) -- true = create if not exists
    local count = 0
    
    if reader then
        local line = reader:readLine()
        while line do
            line = line:match("^%s*(.-)%s*$") -- Trim whitespace
            if line ~= "" and string.sub(line, 1, 1) ~= "#" then
                ResetZone.ResetCells[line] = true
                count = count + 1
            end
            line = reader:readLine()
        end
        reader:close()
    end
    
    -- If list is empty, load defaults
    if count == 0 and ResetZone.DefaultListRaw then
        print("ResetZone: Reset list empty. Loading defaults from embedded list...")
        
        -- Parse the raw string
        for line in ResetZone.DefaultListRaw:gmatch("[^\r\n]+") do
            -- Trim whitespace just in case
            line = line:match("^%s*(.-)%s*$")
            if line ~= "" then
                ResetZone.ResetCells[line] = true
                count = count + 1
            end
        end
        
        -- Save immediately so the file is populated for next time
        ResetZone.SaveResetList()
    end
    
    print("ResetZone: Loaded reset list (" .. count .. " chunks).")
end

function ResetZone.SaveResetList()
    local writer = getFileWriter(filename, true, false) -- create, append=false
    if writer then
        writer:write("# ResetZone Reset List\n")
        writer:write("# Generated by ResetZone Mod\n")
        for cell, _ in pairs(ResetZone.ResetCells) do
            writer:write(cell .. "\n")
        end
        writer:close()
        print("ResetZone: Saved reset list.")
    else
        print("ResetZone: Error writing reset list.")
    end
end


Events.OnClientCommand.Add(onClientCommand)
Events.OnGameStart.Add(ResetZone.LoadResetList)
